apiVersion: v1
kind: Service
metadata:
  name: docker-snake
  labels:
    app: docker-snake
spec:
  selector:
    app: docker-snake
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
