apiVersion: v1
kind: Service
metadata:
  name: snake-classic
  labels:
    app: snake-classic
spec:
  selector:
    app: snake-classic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
